"use server";

import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";
import { z } from "zod";
import { loginSchema, signupSchema } from "@/lib/schemas";
import prisma from "@/lib/prisma";

export async function login(prevState: any, formData: FormData) {
  const supabase = await createClient();

  const validatedFields = loginSchema.safeParse({
    email: formData.get("email"),
    password: formData.get("password"),
  });

  if (!validatedFields.success) {
    return {
      errors: validatedFields.error.flatten().fieldErrors,
      message: "Please check your entries.",
    };
  }

  const { email, password } = validatedFields.data;

  const { error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (error) {
    return { message: error.message };
  }

  redirect("/dashboard");
}

export async function signup(prevState: any, formData: FormData) {
  const supabase = await createClient();

  // 1. Validate Fields
  const validatedFields = signupSchema.safeParse({
    name: formData.get("name"),
    email: formData.get("email"),
    password: formData.get("password"),
  });

  if (!validatedFields.success) {
    return {
      errors: validatedFields.error.flatten().fieldErrors,
      message: "Please check your entries.",
    };
  }

  const { email, password, name } = validatedFields.data;

  // 2. Sign Up with Supabase Auth
  const { data: authData, error: authError } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: {
        full_name: name, // Store name in Supabase metadata too
      },
    },
  });

  if (authError) {
    return { message: authError.message };
  }

  // 3. CRITICAL: Create the User in Prisma
  // We use the ID generated by Supabase so they match perfectly.
  if (authData.user) {
    try {
      await prisma.user.create({
        data: {
          id: authData.user.id,
          email: authData.user.email!,
          name: name,
        },
      });
    } catch (dbError) {
      console.error("Error creating user in DB:", dbError);
      // Optional: You might want to delete the Supabase auth user if DB creation fails
      // to keep data clean, but for MVP we will just log it.
    }
  }

  // 4. Redirect
  redirect("/dashboard");
}
